/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
#include "WPILibExtensions/WPILibExtensions.h"
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static SmartCANJaguar* driveTrainRightBack;
	static SmartCANJaguar* driveTrainLeftBack;
	static SmartCANJaguar* driveTrainRightFront;
	static SmartCANJaguar* driveTrainLeftFront;
	static SmartGyro* driveTrainGyro;
	static Solenoid* launcherSolenoid;
	static SmartCANJaguar* collectorRightRoller;
	static SmartCANJaguar* collectorLeftRoller;
	static Servo* collectorAngleAdjuster;
	static DigitalInput* collectorHighLimit;
	static DigitalInput* collectorLowLimit;
	static StallableAnalogEncoder* collectorElevationEncoder;
	static DoubleSolenoid* shifterDoubleSolenoid;
	static Compressor* airCompressorCompressor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static AnalogPressureTransducer* launcherLowPressureSwitch;
	static void init();
};
#endif
