/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
#include "WPILibExtensions/WPILibExtensions.h"
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	static bool disableautonomous;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static SmartCANJaguar* driveTrainRightBack;
	static SmartCANJaguar* driveTrainLeftBack;
	static SmartCANJaguar* driveTrainRightFront;
	static SmartCANJaguar* driveTrainLeftFront;
	static SmartGyro* driveTrainGyro;
	static Compressor* launcherCompressor;
	static Solenoid* launcherSolenoidLeft;
	static Solenoid* launcherSolenoidRight;
	static SpeedController* collectorLeftRoller;
	static SpeedController* collectorRightRoller;
	static DoubleSolenoid* shifterDoubleSolenoid;
	static StallableAnalogEncoder* robotRangeFinderUltrasonicSensor;
	static SmartCANJaguar* elevatorAngleAdjuster;
	static StallableAnalogEncoder* elevatorElevationEncoder;
	static StallableAnalogEncoder* dataSendingBatteryCurrent;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS/
	static AnalogPressureTransducer* launcherPressureSwitch;
	static SPI* bling;
	static void init();
private:
};
#endif	
