/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "autoElevator.h"
autoElevator::autoElevator() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elevator);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void autoElevator::Initialize() {
	puts("Testing the elevator...\n");
	Wait(1);
}
// Called repeatedly when this Command is scheduled to run
void autoElevator::Execute() {
	puts("Moving the elevator down...\n");
	Robot::elevator->autoDown();
	Wait(1.5);
	puts("Should hit the Limit Switch now...\n");
	Wait(1);
	puts("Moving the elevator up...\n");
	Robot::elevator->autoUp();
	Wait(1.5);
	puts("Should hit the Limit Switch now...\n");
	Wait(1);
	Robot::elevator->autoStopArm();
}
// Make this return true when this Command no longer needs to run execute()
bool autoElevator::IsFinished() {
	return true;
}
// Called once after isFinished returns true
void autoElevator::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void autoElevator::Interrupted() {
}
