/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "autoDriveTrain.h"
autoDriveTrain::autoDriveTrain() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void autoDriveTrain::Initialize() {
	puts("Testing the drive Train..\n");
}
// Called repeatedly when this Command is scheduled to run
void autoDriveTrain::Execute() {
	puts("Driving Foward half a second...\n");
	Robot::driveTrain->AutoFoward();
	Wait(1);
	Robot::driveTrain->Stop();
	Wait(0.3);
	puts("Driving Reverse half a second...\n");
	Robot::driveTrain->AutoReverse();
	Wait(1);
	Robot::driveTrain->Stop();
	puts ("Drive train test complete!\n");
	Wait(1);
}
// Make this return true when this Command no longer needs to run execute()
bool autoDriveTrain::IsFinished() {
	return true;
}
// Called once after isFinished returns true
void autoDriveTrain::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void autoDriveTrain::Interrupted() {
}
