/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "AutonomousHoldElevatorPos.h"
AutonomousHoldElevatorPos::AutonomousHoldElevatorPos() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elevator);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	holdPercent = Robot::prefs->GetDouble("holdTime", 0.01);
	SetTimeout(holdPercent);
}
// Called just before this Command runs the first time
void AutonomousHoldElevatorPos::Initialize() {
	// TODO this function needs work as to what it's supposed to do *manually* apply some voltage to the motor
	// Robot::elevator->SetSetpoint(holdPercent);
}
// Called repeatedly when this Command is scheduled to run
void AutonomousHoldElevatorPos::Execute() {
	
}
// Make this return true when this Command no longer needs to run execute()
bool AutonomousHoldElevatorPos::IsFinished() {
	return IsTimedOut();
}
// Called once after isFinished returns true
void AutonomousHoldElevatorPos::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousHoldElevatorPos::Interrupted() {
}
