/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "Collect.h"
Collect::Collect() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::collector);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void Collect::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void Collect::Execute() {
	
}
// Make this return true when this Command no longer needs to run execute()
bool Collect::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void Collect::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Collect::Interrupted() {
}
