/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "CollectorPurge.h"
CollectorPurge::CollectorPurge() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::collector);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void CollectorPurge::Initialize() {
	Robot::collector->Collect(false);
}
void CollectorPurge::Execute() {}
bool CollectorPurge::IsFinished() {
	return false;
}
void CollectorPurge::End() {
	Robot::collector->StopRollers();
}
void CollectorPurge::Interrupted() {End();}
