/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */


#include "CollectorFeedWithTimeoutCommand.h"

CollectorFeedWithTimeoutCommand::CollectorFeedWithTimeoutCommand(bool dir, double timeout) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::collector);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	this->dir = dir;
	SetTimeout(timeout);
}

// Called just before this Command runs the first time
void CollectorFeedWithTimeoutCommand::Initialize() {
	Robot::collector->Collect(dir);
}

// Called repeatedly when this Command is scheduled to run
void CollectorFeedWithTimeoutCommand::Execute() {
	
}

// Make this return true when this Command no longer needs to run execute()
bool CollectorFeedWithTimeoutCommand::IsFinished() {
	return IsTimedOut();
}

// Called once after isFinished returns true
void CollectorFeedWithTimeoutCommand::End() {
	Robot::collector->StopRollers();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void CollectorFeedWithTimeoutCommand::Interrupted() {
End();
}
