/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */

/*
 * The default command for the Shifter subsystem, constantly compresses the compressor
 * until it is fully compressed. Will run throughout the match until we are ready to shift gears.
 */

#include "Compress.h"

Compress::Compress() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shifter);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

void Compress::Initialize() {
	Robot::shifter->StartCompressing();
}

void Compress::Execute() {}

bool Compress::IsFinished() {
	return Robot::shifter->IsCompressed();
}

void Compress::End() {
	Robot::shifter->StopCompressing();
}

void Compress::Interrupted() {
	End();
}
