/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "ElevateCollectorToBottom.h"
ElevateCollectorToBottom::ElevateCollectorToBottom() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elevator);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void ElevateCollectorToBottom::Initialize() {
	Robot::elevator->GoToMinPosition();
}
void ElevateCollectorToBottom::Execute() {}
bool ElevateCollectorToBottom::IsFinished() {return true;}
void ElevateCollectorToBottom::End() {}
void ElevateCollectorToBottom::Interrupted() {End();}
