/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "ElevatorCollectorDown.h"
ElevatorCollectorDown::ElevatorCollectorDown() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elevator);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void ElevatorCollectorDown::Initialize() {}
void ElevatorCollectorDown::Execute() {
	Robot::elevator->IncrementSetPoint(false);
}
bool ElevatorCollectorDown::IsFinished() {return false;}
void ElevatorCollectorDown::End() {Robot::elevator->HoldPosition();}
void ElevatorCollectorDown::Interrupted() {End();}
