/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "ElevateCollectorToShooter.h"

ElevateCollectorToShooter::ElevateCollectorToShooter() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elevator);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

void ElevateCollectorToShooter::Initialize() {Robot::elevator->GoToShootPosition();}

void ElevateCollectorToShooter::Execute() {}

bool ElevateCollectorToShooter::IsFinished() {
	return true;
}

void ElevateCollectorToShooter::End() {}
void ElevateCollectorToShooter::Interrupted() {End();}
