/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */


#include "ElevateCollectorToTop.h"

ElevateCollectorToTop::ElevateCollectorToTop() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elevator);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

void ElevateCollectorToTop::Initialize() {
	Robot::elevator->GoToMaxPosition();
}

void ElevateCollectorToTop::Execute() {}
bool ElevateCollectorToTop::IsFinished() {return true;}
void ElevateCollectorToTop::End() {}
void ElevateCollectorToTop::Interrupted() {}
