/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */


#include "ElevatorOff.h"

ElevatorOff::ElevatorOff() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elevator);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void ElevatorOff::Initialize() {
	Robot::elevator->HoldPosition();
}

// Called repeatedly when this Command is scheduled to run
void ElevatorOff::Execute() {
	
}

// Make this return true when this Command no longer needs to run execute()
bool ElevatorOff::IsFinished() {
	return true;
}

// Called once after isFinished returns true
void ElevatorOff::End() {
	Robot::elevator->HoldPosition();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ElevatorOff::Interrupted() {
	End();
}
