/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "LauchBall.h"
LauchBall::LauchBall() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::launcher);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

void LauchBall::Initialize() {
	skipMe = Robot::airCompressor->IsLowPressure();
	if (!skipMe) {
		
	} else {
		printf("You're not compressed enough to launch a ball!\n");
	}
}

void LauchBall::Execute() {
	if (!skipMe) {
		
	}
}

bool LauchBall::IsFinished() {
	return true;
}

void LauchBall::End() {
	
}

void LauchBall::Interrupted() {
}
