/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "LaunchBall.h"
LaunchBall::LaunchBall() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::launcher);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void LaunchBall::Initialize() {
	Robot::launcher->OpenTank();
}
void LaunchBall::Execute() {
	puts("You're launching the ball");
}
bool LaunchBall::IsFinished() {
	return false;
}
void LaunchBall::End() {
	puts("you're done launching the ball");
	Robot::launcher->CloseTank();
}
void LaunchBall::Interrupted() {
	puts("you're interrupting the command");
	End();
}
