/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */


#include "SwitchGear.h"

SwitchGear::SwitchGear() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

void SwitchGear::Initialize() {
	Robot::driveTrain->SwitchGear();
	if (Robot::driveTrain->IsLowGear()) {
		printf("You're now in low gear\n");
	}
	else {
		printf("You're now in high gear");
	}
}

void SwitchGear::Execute() {}

bool SwitchGear::IsFinished() {return true;}

void SwitchGear::End() {}

void SwitchGear::Interrupted() {}
