/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "SwitchGear.h"
SwitchGear::SwitchGear() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shifter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void SwitchGear::Initialize() {

}
void SwitchGear::Execute() {}
bool SwitchGear::IsFinished() {return true;}
void SwitchGear::End() {}
void SwitchGear::Interrupted() {}
