/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */


#include "TalonCalibratePositive.h"

TalonCalibratePositive::TalonCalibratePositive() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::collector);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void TalonCalibratePositive::Initialize() {
	Robot::collector->leftRoller->Set(1.0f);
	Robot::collector->rightRoller->Set(1.0f);
}

// Called repeatedly when this Command is scheduled to run
void TalonCalibratePositive::Execute() {

}

// Make this return true when this Command no longer needs to run execute()
bool TalonCalibratePositive::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void TalonCalibratePositive::End() {
	Robot::collector->leftRoller->Set(0.0f);
	Robot::collector->rightRoller->Set(0.0f);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TalonCalibratePositive::Interrupted() {
	End();
}
