/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef BLING_H
#define BLING_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../WPILibExtensions/WPILibExtensions.h"
#include "I2C.h"
class Bling: public Subsystem {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Bling();
	typedef enum PATTERN {
		OFF=0,
		BLUE_SOLID=1,
		BLUE_BLINKING=2,
		GREEN_SOLID=3,
		GREEN_BLINKING=4,
		RAINBOW_EXPLOSION=5,
		// error
		RED_BLINKING=6,
		// autonomous
		PURPLE_SOLID=7,
		PURPLE_BLINKING=8,
	};
	void SetPattern(PATTERN pattern);
	void Execute();
private:
	PATTERN pattern;
	I2C* arduino;
	void InitializeBackgroundTask();
};
#endif
