/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "Collector.h"
#include "../Robotmap.h"
Collector::Collector() : Subsystem("Collector") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	leftRoller = RobotMap::collectorLeftRoller;
	rightRoller = RobotMap::collectorRightRoller;
	angleAdjuster = RobotMap::collectorAngleAdjuster;
	elevationEncoder = RobotMap::collectorElevationEncoder;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
void Collector::InitDefaultCommand() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void Collector::Elevate(bool dir){
	if(dir && CanMoveElevator())
		angleAdjuster->Set(1.0f);
	else if(!dir && CanMoveElevator())
		angleAdjuster->Set(-1.0f);
}
bool Collector::CanMoveElevator() {
	return elevationEncoder->IsStall();
}
void Collector::Collect(bool dir){
	//false = purge, true = collect
	if(dir){
		leftRoller->Set(1.0f);
		rightRoller->Set(-1.0f);
	}
	else if(!dir){
		leftRoller->Set(-1.0f);
		rightRoller->Set(1.0f);
	}
}
void Collector::StopRollers(){
	leftRoller->Set(0.0f);
	rightRoller->Set(0.0f);
}
