/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef COLLECTOR_H
#define COLLECTOR_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../WPILibExtensions/WPILibExtensions.h"
class Collector: public Subsystem {
private:
	//BEGIN DEBUG CODE
	//float realSpeed;
	//END DEBUG CODE
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* leftRoller;
	SpeedController* rightRoller;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Collector();
	void InitDefaultCommand();
	void Collect(bool feedIn);
	void StopRollers();
	bool isCollectorReady;
	void autoStopRollers();
	//BEGIN DEBUG CODE
	//void SetSpeed(float speed);
	//float GetSpeed();
	//END DEBUG CODE
};
#endif
