/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "Collector.h"
#include "../Robotmap.h"
Collector::Collector() : Subsystem("Collector") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	rightRoller = RobotMap::collectorRightRoller;
	leftRoller = RobotMap::collectorLeftRoller;
	angleAdjuster = RobotMap::collectorAngleAdjuster;
	highLimit = RobotMap::collectorHighLimit;
	lowLimit = RobotMap::collectorLowLimit;
	elevationEncoder = RobotMap::collectorElevationEncoder;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	rollers = RobotMap::collectorRollers;
}
void Collector::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void Collector::Run() {
	//Collector code here... Take in a bool to decide between purge/collect?
}
void Collector::Elevate(bool dir){
	if(dir && CanMoveElevatorUp())
		angleAdjuster->Set(1.0f);
	else if(!dir && CanMoveElevatorDown())
		angleAdjuster->Set(-1.0f);
}
bool Collector::IsMaxHeight() {
	return LimitPressed(highLimit);
}
bool Collector::IsMinHeight() {
	return LimitPressed(lowLimit);
}
bool Collector::CanMoveElevatorUp() {
    return CanMoveElevator(true);
}
bool Collector::CanMoveElevatorDown() {
    return CanMoveElevator(false);
}
// this is private 
bool Collector::CanMoveElevator(bool dir) {
	//false = down, true = up
	bool limit;
	if(!dir)
		limit = LimitPressed(lowLimit);
	else
		limit = LimitPressed(highLimit);
	return limit || elevationEncoder->IsStall();
}
void Collector::Collect(bool dir){
	//false = purge, true = collect
	if(dir){
		rollers->Set(1.0f);
	}
	else if(!dir){
		rollers->Set(-1.0f);
	}
}
void Collector::StopRollers(){
	rollers->Off();
}
