/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef DRIVE_TRAIN_H
#define DRIVE_TRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../WPILibExtensions/WPILibExtensions.h"
class DriveTrain : public Subsystem {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SmartCANJaguar* rightBack;
	SmartCANJaguar* leftBack;
	SmartCANJaguar* rightFront;
	SmartCANJaguar* leftFront;
	DoubleSolenoid* doubleSolenoid;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DriveTrain();
	void InitDefaultCommand();
	void SwitchGear();
	bool IsLowGear();
	void Drive(float joyX, float joyY, float joyTwist, float robAng);

private:
	bool isFieldOriented;
	bool isFinesseMode;
	bool isTankDriveMode;
	bool lowGear;
	
	float rightFront;
	float rightBack;
	float leftFront;
	float leftBack;
};
#endif
