/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef ELEVATOR_H
#define ELEVATOR_H
#include "Commands/PIDSubsystem.h"
#include "WPILib.h"
#include "../WPILibExtensions/WPILibExtensions.h"
#define ELEVATOR_UP 1.4
#define ELEVATOR_DOWN .2
#define ELEVATOR_SHOOTPOS 2.42
class Elevator: public PIDSubsystem {
	//BEGIN DEBUG CODE
	//private:
	//float angleSpeed;
	//END DEBUG CODE
 public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SmartCANJaguar* angleAdjuster;
	StallableAnalogEncoder* elevationEncoder;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Elevator();
	double ReturnPIDInput();
	void UsePIDOutput(double output);
	void InitDefaultCommand();
	bool NotOKToMove();
	void GoToShootPosition();
	void GoToMaxPosition();
	void GoToMinPosition();
	void HoldPosition();
	//BEGIN DEBUG CODE
	//void SetAngleSpeed(float swag);
	//float GetAngleSpeed();
	//END DEBUG CODE
	void IncrementSetPoint(bool up);
 private:
	bool lastManualDirectionUp;
};
#endif
