/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef ELEVATOR_H
#define ELEVATOR_H
#include "Commands/PIDSubsystem.h"
#include "WPILib.h"
#include "../WPILibExtensions/WPILibExtensions.h"
#define ELEVATOR_UP 4.03
#define ELEVATOR_DOWN 2.87
#define ELEVATOR_SHOOTPOS 3.76
class Elevator: public PIDSubsystem {
 public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SmartCANJaguar* angleAdjuster;
	StallableAnalogEncoder* elevationEncoder;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Elevator();
	double ReturnPIDInput();
	void UsePIDOutput(double output);
	void InitDefaultCommand();
	bool NotOKToMove();
	void GoToShootPosition();
	void GoToMaxPosition();
	void GoToMinPosition();
};
#endif
