/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "Launcher.h"
#include "../Robotmap.h"
#include "../Robot.h"
const int lowPressureLimitDflt = 60;
int Launcher::lowPressureLimit = 0;

Launcher::Launcher() : Subsystem("Launcher") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	solenoidLeft = RobotMap::launcherSolenoidLeft;
	solenoidRight = RobotMap::launcherSolenoidRight;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	pressureTransducer = RobotMap::launcherLowPressureSwitch;
	lowPressureLimit = Robot::prefs->GetInt("LauncherLowPressureLimit", lowPressureLimitDflt);
}
    
void Launcher::InitDefaultCommand() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void Launcher::OpenTank() {
	solenoidLeft->Set(true);
	solenoidRight->Set(true);
}
void Launcher::CloseTank() {
	solenoidLeft->Set(false);
	solenoidRight->Set(false);
}
//TODO: Constant may need to be calibrated
bool Launcher::IsLowPressure() {
	float PSI = pressureTransducer->GetPressurePSI();
	if (PSI <= lowPressureLimit){
		return true;
	}		
	else 
		return false;
}

bool Launcher::AreTanksOpen() {
	return solenoidLeft->Get() && solenoidRight->Get();
}
//BEGIN DEBUG CODE
/*void Launcher::Launch(){
	solenoidLeft->Set(true);
	solenoidRight->Set(true);
	Wait(1.5);
	solenoidLeft->Set(false);
	solenoidRight->Set(false);
}*/
//END DEBUG CODE
