/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef ROBOTSTATUS_H
#define ROBOTSTATUS_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../WPILibExtensions/WPILibExtensions.h"
class RobotStatus: public Subsystem {
private:
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	RobotStatus();
	void InitDefaultCommand();
	typedef enum StatusCode
	{
		HAPPY,
		LAUNCHER_ERROR,
		SHIFT_ERROR,
		SHIFT_HIGH,
		SHIFT_LOW,
		LAUNCHER_SHOOTING,
		LAUNCHER_READY,
		LAST_ERROR
		
	} StatusCode;
	void SetError(StatusCode code);
	
	
	
};
#endif
