/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */


#ifndef ROBOTSTATUS_H
#define ROBOTSTATUS_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../WPILibExtensions/WPILibExtensions.h"

class RobotStatus: public Subsystem {
private:

public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	RobotStatus();
	void InitDefaultCommand();
	typedef enum StatusCode
	{
		
		LAUNCHER_READY,
		LAUNCHER_UNDREADY,
		LAUNCHER_ERROR,
		LAST_ERROR
		
	} StatusCode;
	
	
	
};

#endif
