/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#include "Vision.h"
#include "../Robotmap.h"
Vision::Vision() : Subsystem("Vision") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	visionTable = 0;
	
}
    
void Vision::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
bool Vision::IsHot(){
	bool isHot = true;
	try
	{
		if (visionTable == 0)
			visionTable = NetworkTable::GetTable("visionTable");
		isHot = visionTable->GetBoolean("Hot");
	}
	catch(...)
	{
		printf("Network Table IsHot failed\n");
	}
	return isHot;
	
}
